#Set image dasar 
FROM mysql:latest

#Set MySQL host
ENV MYSQL_HOST=127.0.0.1

#Set MySQL port
ENV MYSQL_PORT=3306

#Set MySQL user
ENV MYSQL_USER=username

#Set MySQL password
ENV MYSQL_PASSWORD=password

#Set MySQL root password
ENV MYSQL_ROOT_PASSWORD=ayampanggang

#Set MySQL database name
ENV MYSQL_DATABASE=Redlock

#Set Copy DB ke dalam docker
COPY redlock-db.sql /docker-entrypoint-initdb.d/

#Buka port 3306
EXPOSE 3306