#Set image dasar dan versi PHP
FROM php:8.1-apache

#Copy file php ke /var/www/html/
COPY redlock-web-2.0 /var/www/html/ 

# Menentukan pemilik dari www-data 
RUN chown -R www-data:www-data /var/www/html

#Menentukan izin untuk /var/www/html
RUN chmod -R 755 /var/www/html

#Untuk mencari semua file di dalam folder /var/www/html untuk di ganti kepemilikan menjadi u dan g
RUN find /var/www/html -type d -exec chmod g+s {} \;

#Install mysql untuk PHP
RUN docker-php-ext-install mysqli pdo pdo_mysql 


#Membuka port 80
EXPOSE 80 
